
import json
from typing import Dict, Any, List
from datetime import datetime
from pathlib import Path
import pandas as pd


class ReportGenerator:
    
    def __init__(self, output_dir: str = "outputs"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
    
    def generate_html_report(self, agent_results: Dict[str, Any], 
                            dataset_name: str = "Analysis") -> str:
        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Data Analysis Report - {dataset_name}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
            border-left: 4px solid #3498db;
            padding-left: 15px;
        }}
        h3 {{
            color: #7f8c8d;
        }}
        .agent-section {{
            background-color: #f8f9fa;
            border-left: 4px solid #3498db;
            padding: 15px;
            margin: 15px 0;
            border-radius: 4px;
        }}
        .metric {{
            display: inline-block;
            background-color: #ecf0f1;
            padding: 10px 15px;
            margin: 5px;
            border-radius: 4px;
            font-weight: bold;
        }}
        .success {{
            color: #27ae60;
        }}
        .error {{
            color: #e74c3c;
        }}
        .timestamp {{
            color: #95a5a6;
            font-size: 0.9em;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background-color: #3498db;
            color: white;
        }}
        tr:hover {{
            background-color: #f5f5f5;
        }}
        .insight-list {{
            background-color: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin: 15px 0;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #7f8c8d;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Data Analysis Report</h1>
        <p><strong>Dataset:</strong> {dataset_name}</p>
        <p class="timestamp">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        
        {self._generate_sections_html(agent_results)}
        
        <div class="footer">
            <p>Generated by Data-Analysis-Agent | Automated EDA & AutoML Pipeline</p>
        </div>
    </div>
</body>
</html>
        """
        
        # Save report
        report_filename = f"report_{dataset_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        report_path = self.output_dir / report_filename
        
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return str(report_path)
    
    def _generate_sections_html(self, agent_results: Dict[str, Any]) -> str:
        html = ""
        
        for agent_name, result in agent_results.items():
            if isinstance(result, dict):
                html += f"""
        <div class="agent-section">
            <h2>{agent_name}</h2>
            {self._dict_to_html(result)}
        </div>
                """
        
        return html
    
    def _dict_to_html(self, data: Any, level: int = 0) -> str:
        if isinstance(data, dict):
            html = ""
            for key, value in data.items():
                if isinstance(value, (list, dict)):
                    html += f"<h3>{key}</h3>"
                    html += self._dict_to_html(value, level + 1)
                else:
                    html += f"<div class='metric'><strong>{key}:</strong> {value}</div>"
            return html
        elif isinstance(data, list):
            if len(data) == 0:
                return ""
            
            if isinstance(data[0], dict):
                html = "<table>"
                # Header
                headers = list(data[0].keys())
                html += "<tr>" + "".join(f"<th>{h}</th>" for h in headers) + "</tr>"
                # Rows
                for item in data:
                    html += "<tr>" + "".join(f"<td>{item.get(h, '')}</td>" for h in headers) + "</tr>"
                html += "</table>"
                return html
            else:
                return "<ul>" + "".join(f"<li>{item}</li>" for item in data) + "</ul>"
        else:
            return str(data)
    
    def generate_json_report(self, agent_results: Dict[str, Any], 
                            dataset_name: str = "Analysis") -> str:
        report_data = {
            'timestamp': datetime.now().isoformat(),
            'dataset_name': dataset_name,
            'agent_results': agent_results,
        }
        
        report_filename = f"report_{dataset_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        report_path = self.output_dir / report_filename
        
        with open(report_path, 'w', encoding='utf-8') as f:
            json.dump(report_data, f, indent=2, default=str)
        
        return str(report_path)
    
    def generate_summary(self, agent_results: Dict[str, Any]) -> str:
        summary = "=== Data Analysis Summary ===\n\n"
        
        for agent_name, result in agent_results.items():
            summary += f"\n{agent_name}:\n"
            summary += "-" * len(agent_name) + "\n"
            
            if isinstance(result, dict):
                summary += self._dict_to_text(result, indent=2)
        
        return summary
    
    def _dict_to_text(self, data: Any, indent: int = 0) -> str:
        text = ""
        prefix = " " * indent
        
        if isinstance(data, dict):
            for key, value in data.items():
                if isinstance(value, (list, dict)):
                    text += f"{prefix}{key}:\n"
                    text += self._dict_to_text(value, indent + 2)
                else:
                    text += f"{prefix}{key}: {value}\n"
        elif isinstance(data, list):
            for item in data:
                if isinstance(item, dict):
                    text += self._dict_to_text(item, indent)
                else:
                    text += f"{prefix}• {item}\n"
        
        return text
